### ISSUE TITLE
Rerrange some Sorting Algorithms in Sorting folder. 

### ISSUE THREAD

**Issue by kumar007ambi** [serverx-org/DSA-MASTERY#26]
Previously I have contributed algo on Sorting,now seeing The algos correctly belongs to Sorting algorithm folder.
@gautamankoji Please assign this issue to fix it.

**Comment by kumar007ambi** [comment]
@gautamankoji What i have seen Some of Sorting algorithms are different folders,some of algorithms are already present in Sorting Folder. So I want to know to that i should delete the same algorithms or Move all algorithms in sorting folder to resolve this issue.Please give me your suggestion🙌

**Comment by gautamankoji** [comment]
if you can contribute additional content beyond what's already there, feel free to submit a pull request, otherwise no need
the structure can be reorganized at any time, you're welcome to add more algorithms if you'd like

**Comment by kumar007ambi** [comment]
@gautamankoji Okay, Then i would contribute Algo related problems for sure
