### ISSUE TITLE
Tree Realated Problem

### ISSUE THREAD

**Issue by kumar007ambi** [serverx-org/DSA-MASTERY#53]
@gautamankoji I want to add Tree traversal realated Problem

**Comment by gautamankoji** [comment]
sure work on it!

**Comment by kumar007ambi** [comment]
@gautamankoji I want to add two more problem on Tree Data Structure

**Comment by gautamankoji** [comment]
> @gautamankoji I want to add two more problem on Tree Data Structure

sure, if possible work on decision Tree and random forest too

**Comment by kumar007ambi** [comment]
> > @gautamankoji I want to add two more problem on Tree Data Structure
> 
> sure, if possible work on decision Tree and random forest too
I am willing to add Height of Binary Tree and Level Order Traversal Problem,If you provide the Problem name or description then i will try to adding it.

**Comment by gautamankoji** [comment]
> I am willing to add Height of Binary Tree and Level Order Traversal Problem,If you provide the Problem name or description then i will try to adding it.

Level Order Traversal of a Binary Tree
Maximum Depth of Binary Tree
Number of Leaf Nodes in a Binary Tree
